title: Westgaard
description: This is not a blog
author: "Jon Arne Westgard"

theme: minimal-mistakes
show_excerpts: true

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md
include:
    - _pages

exclude: 
    - .gitignore
    - LICENSE
    - README.md
