title: Westgaard
description: This is not a blog
author: "Jon Arne Westgard"

theme: minima
show_excerpts: true

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md
include:
    - _pages

exclude: 
    - .gitignore
    - LICENSE
    - README.md

# Set which comment system to use
comments:
  provider:            giscus
  
giscus:
  data-repo="Westgaard/Westgaard.github.io"
  data-repo-id="R_kgDOIbS9-g"
  data-category="Announcements"
  data-category-id="DIC_kwDOIbS9-s4CSh8Q"
  data-mapping="pathname"
  data-strict="0"
  data-reactions-enabled="1"
  data-emit-metadata="0"
  data-input-position="top"
  data-theme="light"
  data-lang="en"
  data-loading="lazy"
  crossorigin="anonymous"
