title: Westgaard
description: This is not a blog
author: "Jon Arne Westgard"

theme: minima
show_excerpts: true

include:
    - _pages

exclude: 
    - .gitignore
    - LICENSE
    - README.md
